-- NOTE module DDL (06-notes.md §4). This file is the reviewable source of truth;
-- the *executable* copy is inlined as migration v6 'notes' in
-- electron/db/migrate.ts (the migration runner is an inline registry, not a
-- file loader — see S4.4 decision in docs/dev/PROGRESS.md).
--
-- New tables: notes, note_links, tags, tag_refs (polymorphic), notebooks,
-- fts_notes (FTS5 virtual table for NOTE-03 full-text search).
--
-- Hard constraints honoured (00-architecture §5):
--  - PRAGMA foreign_keys = ON is set by db/connection.ts (§5.1).
--  - paragraphs.id / chapters.id / books.id are TEXT stable UUIDs (§5.2).
--  - paragraph_id FK on notes is ON DELETE SET NULL — segment-edit deletion
--    degrades the note to a free note (loses its paragraph anchor but is NOT
--    lost) per 06-notes.md §1.2.
--  - Stable IDs are never dropped/regenerated by this migration (§5.5).

-- ---------------------------------------------------------------------------
-- notes (NOTE-01 / NOTE-05 main table)
-- ---------------------------------------------------------------------------
-- Markdown source is the single source of truth; rendered HTML is never stored
-- (avoids dual-source staleness). book_id / chapter_id / paragraph_id are
-- non-exclusive: binding to a paragraph auto-backfills chapter/book via the
-- service layer (§7.6). All three are nullable = free-standing note.
-- paragraph_id is the NOTE-05 sidebar entry point (idx_notes_paragraph).
CREATE TABLE IF NOT EXISTS notes (
    id            TEXT    PRIMARY KEY,                 -- UUID v4, app-generated
    title         TEXT    NOT NULL DEFAULT '',
    content       TEXT    NOT NULL DEFAULT '',          -- Markdown source (only storage)
    book_id       TEXT    NULL,                         -- FK books.id (nullable: free note)
    chapter_id    TEXT    NULL,                         -- FK chapters.id (nullable)
    paragraph_id  TEXT    NULL,                         -- FK paragraphs.id (NOTE-05 sidebar key)
    notebook_id   TEXT    NULL,                         -- FK notebooks.id (nullable: ungrouped)
    word_count    INTEGER NOT NULL DEFAULT 0,           -- redundant: list display/sort
    pinned        INTEGER NOT NULL DEFAULT 0,           -- 0/1 pin to top
    created_at    INTEGER NOT NULL,                     -- unix ms
    updated_at    INTEGER NOT NULL,                     -- unix ms
    deleted_at    INTEGER NULL,                         -- soft delete (NULL = live)
    FOREIGN KEY (book_id)      REFERENCES books(id)      ON DELETE SET NULL,
    FOREIGN KEY (chapter_id)   REFERENCES chapters(id)   ON DELETE SET NULL,
    FOREIGN KEY (paragraph_id) REFERENCES paragraphs(id) ON DELETE SET NULL,
    FOREIGN KEY (notebook_id)  REFERENCES notebooks(id)  ON DELETE SET NULL
);

-- NOTE-05 high-frequency path: reading sidebar queries notes by paragraph.
CREATE INDEX IF NOT EXISTS idx_notes_paragraph ON notes(paragraph_id, deleted_at);
-- Notebook-grouped browsing.
CREATE INDEX IF NOT EXISTS idx_notes_notebook  ON notes(notebook_id, deleted_at, updated_at);
-- Chapter/book-scoped note lists.
CREATE INDEX IF NOT EXISTS idx_notes_chapter   ON notes(chapter_id, deleted_at);
CREATE INDEX IF NOT EXISTS idx_notes_book      ON notes(book_id, deleted_at);
-- Default list sort: newest first among live notes.
CREATE INDEX IF NOT EXISTS idx_notes_updated   ON notes(deleted_at, updated_at DESC);

-- ---------------------------------------------------------------------------
-- note_links (NOTE-02 wiki-link parse results + backlinks source)
-- ---------------------------------------------------------------------------
-- Derived data: re-computed in full on every note save (transaction deletes
-- all old rows for source_note_id, re-scans content for [[ ]] and re-inserts).
-- target_type ∈ 'chapter' | 'paragraph' | 'term' | 'note'. Failed resolutions
-- fall back to type 'term' with target_id = normalizedTermKey(rawText) so that
-- a future dictionary entry auto-restores the backlink without editing the note.
-- target_alias preserves the user's original [[ ]] inner text for hover/repair.
CREATE TABLE IF NOT EXISTS note_links (
    id              TEXT    PRIMARY KEY,                -- UUID v4
    source_note_id  TEXT    NOT NULL,                   -- FK notes.id (the note containing the link)
    target_type     TEXT    NOT NULL,                   -- 'chapter' | 'paragraph' | 'term' | 'note'
    target_id       TEXT    NOT NULL,                   -- target entity id / normalized term key
    target_alias    TEXT    NULL,                       -- original [[ ]] inner text (hover / invalid prompt)
    display_text    TEXT    NULL,                       -- [[target|display]] pipe display text
    position        INTEGER NOT NULL DEFAULT 0,         -- ordinal link index (for highlight positioning)
    created_at      INTEGER NOT NULL,
    FOREIGN KEY (source_note_id) REFERENCES notes(id) ON DELETE CASCADE
);

-- Backlinks query core index: given a target, find all notes referencing it.
CREATE INDEX IF NOT EXISTS idx_note_links_target ON note_links(target_type, target_id);
-- Forward: list all out-links of a note.
CREATE INDEX IF NOT EXISTS idx_note_links_source ON note_links(source_note_id);
-- Uniqueness: same note → same target stored once (position = first occurrence).
CREATE UNIQUE INDEX IF NOT EXISTS uq_note_links ON note_links(source_note_id, target_type, target_id);

-- ---------------------------------------------------------------------------
-- tags (NOTE-03 tag dictionary, polymorphic — shared with SRH)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tags (
    id          TEXT    PRIMARY KEY,                    -- UUID v4
    name        TEXT    NOT NULL UNIQUE,                 -- tag name (unique)
    color       TEXT    NULL,                            -- optional color token
    created_at  INTEGER NOT NULL
);

-- ---------------------------------------------------------------------------
-- tag_refs (polymorphic tag references: note / paragraph / book)
-- ---------------------------------------------------------------------------
-- ref_type distinguishes which entity type a tag is attached to, so a single
-- table serves notes (NOTE-03), paragraphs and books (SRH-02 filtering).
CREATE TABLE IF NOT EXISTS tag_refs (
    id          TEXT    PRIMARY KEY,                    -- UUID v4
    tag_id      TEXT    NOT NULL,                       -- FK tags.id
    ref_type    TEXT    NOT NULL,                       -- 'note' | 'paragraph' | 'book'
    ref_id      TEXT    NOT NULL,                       -- corresponding entity id
    created_at  INTEGER NOT NULL,
    FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE,
    UNIQUE (tag_id, ref_type, ref_id)                   -- no duplicate tag on same target
);

CREATE INDEX IF NOT EXISTS idx_tag_refs_target ON tag_refs(ref_type, ref_id);
CREATE INDEX IF NOT EXISTS idx_tag_refs_tag    ON tag_refs(tag_id);

-- ---------------------------------------------------------------------------
-- notebooks (NOTE-03 notebook grouping, single-level nesting)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS notebooks (
    id          TEXT    PRIMARY KEY,                    -- UUID v4
    name        TEXT    NOT NULL,
    parent_id   TEXT    NULL,                           -- self-ref (nullable: root)
    sort_order  INTEGER NOT NULL DEFAULT 0,
    icon        TEXT    NULL,                           -- optional icon identifier
    created_at  INTEGER NOT NULL,
    updated_at  INTEGER NOT NULL,
    FOREIGN KEY (parent_id) REFERENCES notebooks(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_notebooks_parent ON notebooks(parent_id, sort_order);

-- ---------------------------------------------------------------------------
-- fts_notes (NOTE-03 FTS5 virtual table for note full-text search)
-- ---------------------------------------------------------------------------
-- Independent from fts_paragraphs (SRH-owned): different content intent, separate
-- table allows independent ranking. unicode61 tokenizer (06-notes.md §11 open
-- question: upgrade to trigram if user feedback demands word-level CJK search).
-- Triggers sync the FTS index on note INSERT/UPDATE/soft-delete.
CREATE VIRTUAL TABLE IF NOT EXISTS fts_notes USING fts5(
    note_id UNINDEXED,                                  -- links to notes.id (not indexed)
    title,
    content,
    tokenize = 'unicode61 remove_diacritics 2'
);

-- notes INSERT → add to FTS index (only when not soft-deleted).
CREATE TRIGGER IF NOT EXISTS trg_notes_ai AFTER INSERT ON notes
WHEN new.deleted_at IS NULL
BEGIN
    INSERT INTO fts_notes(note_id, title, content) VALUES (new.id, new.title, new.content);
END;

-- notes DELETE (hard) → remove from FTS index.
CREATE TRIGGER IF NOT EXISTS trg_notes_ad AFTER DELETE ON notes
BEGIN
    DELETE FROM fts_notes WHERE note_id = old.id;
END;

-- notes UPDATE (title/content changed) → re-sync FTS index (only if live).
CREATE TRIGGER IF NOT EXISTS trg_notes_au AFTER UPDATE OF title, content ON notes
WHEN new.deleted_at IS NULL
BEGIN
    DELETE FROM fts_notes WHERE note_id = old.id;
    INSERT INTO fts_notes(note_id, title, content) VALUES (new.id, new.title, new.content);
END;

-- notes soft-delete (deleted_at goes NULL→non-NULL) → evict from FTS index.
CREATE TRIGGER IF NOT EXISTS trg_notes_softdel AFTER UPDATE OF deleted_at ON notes
WHEN new.deleted_at IS NOT NULL AND old.deleted_at IS NULL
BEGIN
    DELETE FROM fts_notes WHERE note_id = new.id;
END;
