-- Reading module DDL. This file is the reviewable source of truth;
-- the *executable* copy is inlined as migration v5 'reading' in
-- electron/db/migrate.ts (the migration runner is an inline registry, not a
-- file loader — see S4.4 decision in docs/dev/PROGRESS.md).
--
-- Current schema keeps reading_progress only. The standalone reading workbench
-- and bookmarks surface were removed during the library-detail consolidation.
--
-- Hard constraints honoured:
--  - PRAGMA foreign_keys = ON is set by db/connection.ts (00-arch §5.1).
--  - paragraphs.id is TEXT stable UUID; the implicit rowid is untouched (§5.2).
--  - Stable IDs are never dropped/regenerated by this migration (§5.5).

-- ---------------------------------------------------------------------------
-- reading_progress
-- ---------------------------------------------------------------------------
-- One row per book (PK = book_id): records the most-recent reading position to
-- segment granularity. paragraph_id is the primary anchor (stable UUID,
-- survives re-parse); scroll_ratio is a within-paragraph fine adjustment.
CREATE TABLE IF NOT EXISTS reading_progress (
    book_id      TEXT    NOT NULL,                 -- FK books.id (one row per book)
    chapter_id   TEXT    NOT NULL,                 -- current chapter (FK chapters.id)
    paragraph_id TEXT    NOT NULL,                 -- top visible paragraph (FK paragraphs.id)
    scroll_ratio REAL    NOT NULL DEFAULT 0,       -- 0..1 within-chapter fine adjustment
    read_seconds INTEGER NOT NULL DEFAULT 0,       -- accumulated reading seconds (dashboard)
    percent      REAL    NOT NULL DEFAULT 0,       -- whole-book percent (display,冗余)
    updated_at   INTEGER NOT NULL,                 -- unix ms
    PRIMARY KEY (book_id),
    FOREIGN KEY (book_id)      REFERENCES books(id)      ON DELETE CASCADE,
    FOREIGN KEY (chapter_id)   REFERENCES chapters(id)   ON DELETE CASCADE,
    FOREIGN KEY (paragraph_id) REFERENCES paragraphs(id) ON DELETE CASCADE
);

-- Library cards sort by "recently read".
CREATE INDEX IF NOT EXISTS idx_reading_progress_updated
    ON reading_progress(updated_at DESC);
