-- RD module DDL (03-reading.md §4). This file is the reviewable source of truth;
-- the *executable* copy is inlined as migration v5 'reading' in
-- electron/db/migrate.ts (the migration runner is an inline registry, not a
-- file loader — see S4.4 decision in docs/dev/PROGRESS.md).
--
-- Two new tables: reading_progress (segment-level) and bookmarks. Both reference
-- paragraphs/chapters/books and MUST declare cascade actions consistent with
-- 00-architecture §5.3 so deleting a book/chapter/segment cleanly removes (or,
-- for the segment-level bookmark, degrades) the dependent rows.
--
-- Hard constraints honoured:
--  - PRAGMA foreign_keys = ON is set by db/connection.ts (00-arch §5.1).
--  - paragraphs.id is TEXT stable UUID; the implicit rowid is untouched (§5.2).
--  - Stable IDs are never dropped/regenerated by this migration (§5.5).

-- ---------------------------------------------------------------------------
-- reading_progress (RD-08, segment-level reading progress)
-- ---------------------------------------------------------------------------
-- One row per book (PK = book_id): records the most-recent reading position to
-- segment granularity. paragraph_id is the primary anchor (stable UUID,
-- survives re-parse); scroll_ratio is a within-paragraph fine adjustment.
-- Crash-safe: written inside db.transaction(); renderer debounces + flushes on
-- hide/unload (03-reading.md §7.3).
CREATE TABLE IF NOT EXISTS reading_progress (
    book_id      TEXT    NOT NULL,                 -- FK books.id (one row per book)
    chapter_id   TEXT    NOT NULL,                 -- current chapter (FK chapters.id)
    paragraph_id TEXT    NOT NULL,                 -- top visible paragraph (FK paragraphs.id)
    scroll_ratio REAL    NOT NULL DEFAULT 0,       -- 0..1 within-chapter fine adjustment
    read_seconds INTEGER NOT NULL DEFAULT 0,       -- accumulated reading seconds (streak/dashboard)
    percent      REAL    NOT NULL DEFAULT 0,       -- whole-book percent (display,冗余)
    updated_at   INTEGER NOT NULL,                 -- unix ms
    PRIMARY KEY (book_id),
    FOREIGN KEY (book_id)      REFERENCES books(id)      ON DELETE CASCADE,
    FOREIGN KEY (chapter_id)   REFERENCES chapters(id)   ON DELETE CASCADE,
    FOREIGN KEY (paragraph_id) REFERENCES paragraphs(id) ON DELETE CASCADE
);

-- Library cards sort by "recently read".
CREATE INDEX IF NOT EXISTS idx_reading_progress_updated
    ON reading_progress(updated_at DESC);

-- ---------------------------------------------------------------------------
-- bookmarks (RD-08, bindable to segment or chapter)
-- ---------------------------------------------------------------------------
-- A single table models both segment-level (paragraph_id NOT NULL) and
-- chapter-level (paragraph_id NULL) bookmarks. When a paragraph is hard-deleted
-- by segment editing, ON DELETE SET NULL degrades the bookmark to chapter-level
-- so the user's marker is never lost (03-reading.md §4.2).
CREATE TABLE IF NOT EXISTS bookmarks (
    id           TEXT    PRIMARY KEY,              -- UUID v4
    book_id      TEXT    NOT NULL,                 -- FK books.id
    chapter_id   TEXT    NOT NULL,                 -- FK chapters.id (always set, locates the chapter)
    paragraph_id TEXT,                             -- nullable: NULL = chapter bookmark, set = segment bookmark
    title        TEXT,                             -- nullable: defaults to first N chars of paragraph/chapter
    note         TEXT,                             -- nullable: user note
    color        TEXT,                             -- nullable: reserved label color (multi-color)
    created_at   INTEGER NOT NULL,
    updated_at   INTEGER NOT NULL,
    FOREIGN KEY (book_id)      REFERENCES books(id)      ON DELETE CASCADE,
    FOREIGN KEY (chapter_id)   REFERENCES chapters(id)   ON DELETE CASCADE,
    FOREIGN KEY (paragraph_id) REFERENCES paragraphs(id) ON DELETE SET NULL
);

-- Bookmark sidebar: list by book, newest first.
CREATE INDEX IF NOT EXISTS idx_bookmarks_book_created
    ON bookmarks(book_id, created_at DESC);
-- Per-paragraph lookup ("how many bookmarks on this segment") for inline marks.
CREATE INDEX IF NOT EXISTS idx_bookmarks_paragraph
    ON bookmarks(paragraph_id) WHERE paragraph_id IS NOT NULL;
